import { ref, type Ref } from 'vue';
export type Loot = {
  id: number;
  name: string;
  img: string;
  unique?: boolean;
  weight: number;
  minQty?: number;
  maxQty?: number;
};

export const normalLoot: Ref<Loot[]> = ref([
  {
    id: 32,
    name: 'Vial of blood',
    img: '/osrs-tob-loot-simulator/items/vial_of_blood.png',
    weight: 2,
    minQty: 45,
    maxQty: 60,
  },
  { id: 31, name: 'Death rune', img: '/osrs-tob-loot-simulator/items/death_rune.png', weight: 1, minQty: 500, maxQty: 600 },
  { id: 30, name: 'Blood rune', img: '/osrs-tob-loot-simulator/items/blood_rune.png', weight: 1, minQty: 500, maxQty: 600 },
  { id: 4, name: 'Swamp tar', img: '/osrs-tob-loot-simulator/items/swamp_tar.png', weight: 1, minQty: 500, maxQty: 600 },
  { id: 5, name: 'Coal', img: '/osrs-tob-loot-simulator/items/coal.png', weight: 1, minQty: 500, maxQty: 600 },
  { id: 6, name: 'Gold ore', img: '/osrs-tob-loot-simulator/items/gold_ore.png', weight: 1, minQty: 300, maxQty: 360 },
  {
    id: 7,
    name: 'Molten glass',
    img: '/osrs-tob-loot-simulator/items/molten_glass.png',
    weight: 1,
    minQty: 200,
    maxQty: 240,
  },
  {
    id: 8,
    name: 'Adamantite ore',
    img: '/osrs-tob-loot-simulator/items/adamantite_ore.png',
    weight: 1,
    minQty: 130,
    maxQty: 156,
  },
  { id: 9, name: 'Runite ore', img: '/osrs-tob-loot-simulator/items/runite_ore.png', weight: 1, minQty: 60, maxQty: 72 },
  {
    id: 10,
    name: 'Wine of zamorak',
    img: '/osrs-tob-loot-simulator/items/wine_of_zamorak.png',
    weight: 1,
    minQty: 50,
    maxQty: 60,
  },
  {
    id: 11,
    name: 'Potato cactus',
    img: '/osrs-tob-loot-simulator/items/potato_cactus.png',
    weight: 1,
    minQty: 50,
    maxQty: 60,
  },
  {
    id: 12,
    name: 'Grimy cadantine',
    img: '/osrs-tob-loot-simulator/items/grimy_cadantine.png',
    weight: 1,
    minQty: 50,
    maxQty: 60,
  },
  {
    id: 13,
    name: 'Grimy avantoe',
    img: '/osrs-tob-loot-simulator/items/grimy_avantoe.png',
    weight: 1,
    minQty: 40,
    maxQty: 48,
  },
  {
    id: 14,
    name: 'Grimy toadflax',
    img: '/osrs-tob-loot-simulator/items/grimy_toadflax.png',
    weight: 1,
    minQty: 37,
    maxQty: 44,
  },
  {
    id: 15,
    name: 'Grimy kwuarm',
    img: '/osrs-tob-loot-simulator/items/grimy_kwuarm.png',
    weight: 1,
    minQty: 36,
    maxQty: 43,
  },
  {
    id: 16,
    name: 'Grimy irit leaf',
    img: '/osrs-tob-loot-simulator/items/grimy_irit_leaf.png',
    weight: 1,
    minQty: 34,
    maxQty: 40,
  },
  {
    id: 17,
    name: 'Grimy ranarr weed',
    img: '/osrs-tob-loot-simulator/items/grimy_ranarr_weed.png',
    weight: 1,
    minQty: 30,
    maxQty: 36,
  },
  {
    id: 18,
    name: 'Grimy snapdragon',
    img: '/osrs-tob-loot-simulator/items/grimy_snapdragon.png',
    weight: 1,
    minQty: 27,
    maxQty: 32,
  },
  {
    id: 19,
    name: 'Grimy lantadyme',
    img: '/osrs-tob-loot-simulator/items/grimy_lantadyme.png',
    weight: 1,
    minQty: 26,
    maxQty: 31,
  },
  {
    id: 20,
    name: 'Grimy dwarf weed',
    img: '/osrs-tob-loot-simulator/items/grimy_dwarf_weed.png',
    weight: 1,
    minQty: 24,
    maxQty: 28,
  },
  {
    id: 21,
    name: 'Grimy torstol',
    img: '/osrs-tob-loot-simulator/items/grimy_torstol.png',
    weight: 1,
    minQty: 20,
    maxQty: 24,
  },
  { id: 22, name: 'Battlestaff', img: '/osrs-tob-loot-simulator/items/battlestaff.png', weight: 1, minQty: 15, maxQty: 18 },
  {
    id: 23,
    name: 'Rune battleaxe',
    img: '/osrs-tob-loot-simulator/items/rune_battleaxe.png',
    weight: 1,
    minQty: 4,
    maxQty: 4,
  },
  {
    id: 24,
    name: 'Rune platebody',
    img: '/osrs-tob-loot-simulator/items/rune_platebody.png',
    weight: 1,
    minQty: 4,
    maxQty: 4,
  },
  {
    id: 25,
    name: 'Rune chainbody',
    img: '/osrs-tob-loot-simulator/items/rune_chainbody.png',
    weight: 1,
    minQty: 4,
    maxQty: 4,
  },
  {
    id: 26,
    name: 'Palm tree seed',
    img: '/osrs-tob-loot-simulator/items/palm_tree_seed.png',
    weight: 1,
    minQty: 3,
    maxQty: 3,
  },
  { id: 27, name: 'Yew seed', img: '/osrs-tob-loot-simulator/items/yew_seed.png', weight: 1, minQty: 3, maxQty: 3 },
  { id: 28, name: 'Magic seed', img: '/osrs-tob-loot-simulator/items/magic_seed.png', weight: 1, minQty: 3, maxQty: 3 },
  {
    id: 29,
    name: 'Mahogany seed',
    img: '/osrs-tob-loot-simulator/items/mahogany_seed.png',
    weight: 1,
    minQty: 10,
    maxQty: 12,
  },
]);
